### ISSUE TITLE
How to import Google Sheet

### ISSUE THREAD

**Issue by makemoney123** [Multisend-ETH/client-v1#14]
Hello what is the model on google sheet? i try to import a csv from google sheet with Address and Amount, but it dont works. Thanks

**Comment by eltNEG** [comment]
Hi @makemoney123

Short answer: The addresses and amounts must be under a column with title "ADDRESSES" and "AMOUNTS" respectively in sheet 1 of your google sheet.

Please check out this [video tutorial](https://www.useloom.com/share/ae5014b06ad745aa8f88b266a7aaff4f). Let me know if you still have any issue after watching the tutorial


**Example**

<img width="827" alt="Screenshot 2019-06-08 at 3 24 33 PM" src="https://user-images.githubusercontent.com/22221987/59148491-8f94ba00-8a01-11e9-991f-45e5ce7d146a.png">

**Comment by bizmindx** [comment]
am closing issue

**Comment by makemoney123** [comment]
Very Thanks eltNEG, you help me too much, i try about 4 hours headbroken kkkkkk. i put Addresses and Amount in title, but it never work :), so i will try with Caps Lock on. Thanks again.

**Comment by eltNEG** [comment]
@makemoney123, you are welcome.
