### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by eltNEG** [Multisend-ETH/client-v1#2]
**What is the issue about?**
The sentence `We don't expose you to risks by asking` on the landing page does not make complete sense

**How can this be solved**
Change it to `We don't expose you to risks by asking for your private keys`

**Screenshots**
<img width="330" alt="Screenshot 2019-04-30 at 12 09 22 PM" src="https://user-images.githubusercontent.com/22221987/56958112-32bffd00-6b41-11e9-895c-da83f50dce93.png">

**Comment by bizmindx** [comment]
fixed
