### ISSUE TITLE
TXs locked in the smart contract

### ISSUE THREAD

**Issue by iscry** [Multisend-ETH/client-v1#25]
Tried to use https://multisend.co earlier today

But the TXs didn’t get to the destinations

https://etherscan.io/tx/0x0b3d1e716573ccdcfd2ba0151261d4be13a3acc0afc05ce4f0ece4510692e7c3

There were 3 TXs

Does anyone know when the TXs will get through?

Thanks!

**Comment by eltNEG** [comment]
@iscry Sorry for the late response. I think that the issue was caused by the activities on eth network. Also, note that the transaction details shows up when the transaction is confirmed by the ethereum network.

**Comment by iscry** [comment]
Thank you, it all worked out at the end!
