### ISSUE TITLE
Tokens stuck while sending, never received next request after approval was confirmed

### ISSUE THREAD

**Issue by namanjd** [Multisend-ETH/client-v1#28]
As the title suggests, i was trying to send 160 ZGG ERC20 tokens to 158 addresses for which ZGG contract address is **0x37fb2461968C1FEe446183DCaC9727b6dE2FE418**. After confirming the transaction from metamask i.e. first step, **i never  got the other request to approve the tokens to send it to those addresses**. i have the link to that smart contract which is deployed in the first step [here](https://etherscan.io/tx/0xe140ba189782a410f6a60d7eace2a80eaf22b96df5123d21f07abcc888885a91#eventlog).

If anyone can suggest anything, it would be much appreciated. TIA.

**Comment by bizmindx** [comment]
Hello namanjd i am looking into this

**Comment by eltNEG** [comment]
@namanjd You can send to a maximum of 100 addresses at a time. The app shouldn't have allowed you to confirm the first transaction if you have more than 100 addresses. 

Thanks for reporting this.

**Comment by namanjd** [comment]
So there is no way i am getting the stuck tokens back?

**Comment by eltNEG** [comment]
> So there is no way i am getting the stuck tokens back?

What stuck token? Calling the approve method of an ERC20 token doesn't make your token stuck. The purpose of the approve method is to allow another contract or address to spend on your behalf. Moving your token does not have anything to do with multisend.

**Comment by eltNEG** [comment]
I am closing this issue
