### ISSUE TITLE
Make donation easier

### ISSUE THREAD

**Issue by eltNEG** [Multisend-ETH/client-v1#7]
**What is the issue about?**
Make donations to multisend easier by adding a checkbox to send page

**How can this be solved**
Adding a checkbox to send page

**Screenshots**
- 
<img width="1029" alt="Screenshot 2019-04-30 at 1 37 32 PM" src="https://user-images.githubusercontent.com/22221987/56962172-cdbed400-6b4d-11e9-8c25-ddb5ca312dd2.png">

**Comment by bizmindx** [comment]
saw this late though
